# Generate sine256.h (one sine cycle, 256 entries, amplitude 32767).
# Usage: python mksine.py > sine256.h
import math

v = [int(round(32767 * math.sin(2 * math.pi * i / 256))) for i in range(256)]
print('/*')
print(' * 256-entry sine table, one full cycle, amplitude 32767.')
print(' * Generated by mksine.py: round (32767 * sin (2 * pi * i / 256)).')
print(' */')
print('#ifndef SINE256_H')
print('#define SINE256_H')
print()
print('static const short sine256[256] = {')
print(',\n'.join('    ' + ', '.join('%6d' % x for x in v[i:i + 8]) for i in range(0, 256, 8)))
print('};')
print()
print('#endif')
